disabled_rules:
    - trailing_whitespace
    - class_delegate_protocol
    - nesting

cyclomatic_complexity:
    warning: 15
    error: 20

function_body_length:
    warning: 80
    error: 100

line_length:
    warning: 120
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
